// <auto-generated />
namespace Poker.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class _4th_FixStuff : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_4th_FixStuff));
        
        string IMigrationMetadata.Id
        {
            get { return "201502200059019_4th_FixStuff"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
