// <auto-generated />
namespace Poker.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.2-21211")]
    public sealed partial class _3rd_AddScore : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_3rd_AddScore));
        
        string IMigrationMetadata.Id
        {
            get { return "201502161900389_3rd_AddScore"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
